###############################################################
#
## Copyright (©) 2024-2025 David H Hoyt. All rights reserved.
##                 https://srd.cx
##
## Last Updated: 07-MAR-2025 1343 EST by David Hoyt (©)
#
## Intent: Run scan-build on IccMAX Master Branch Release Build
#
## TODO: Refactor for all Windows & UNIX Device Reporting
#
#
###############################################################

name: "Ubuntu Scan Build"

on:
  workflow_dispatch:

jobs:
  build-linux:
    name: Ubuntu Scan Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Entry Banner
        run: |
          echo "====================================="
          echo " Starting Ubu Scan Build Workflow"
          echo "====================================="
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxml2 libxml2-dev nlohmann-json3-dev build-essential \
            cmake libopencl-clang-17-dev libwxgtk3.2-dev libtiff-dev \
            curl git llvm clang-tools clang-17
      - name: Ensure scan-build is installed and accessible
        run: |
          export PATH="/usr/lib/llvm-17/bin:$PATH"
          which scan-build || echo "[!] scan-build not found"
          scan-build --version || echo "[!] scan-build version check failed"
      - name: Clone the DemoIccMAX repository
        run: |
          git clone https://github.com/InternationalColorConsortium/DemoIccMAX.git
          cd DemoIccMAX
          git checkout master
      - name: Configure the build with scan-build
        run: |
          cd DemoIccMAX/Build
          export CC=clang
          export CXX=clang++
          export PATH="/usr/lib/llvm-17/bin:$PATH"
          scan-build cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_BUILD_TYPE=Release -DENABLE_TOOLS=ON -Wno-dev Cmake/
      - name: Run scan-build for static analysis
        run: |
          cd DemoIccMAX/Build
          export PATH="/usr/lib/llvm-17/bin:$PATH"
          scan-build --status-bugs --keep-going -o scan-build-reports make -j$(nproc) || true
        continue-on-error: true

      - name: Upload scan-build reports
        uses: actions/upload-artifact@v4
        with:
          name: scan-build-reports
          path: DemoIccMAX/Build/scan-build-reports

      - name: Evaluate scan-build results
        run: |
          cd DemoIccMAX/Build/scan-build-reports
          if [ "$(find . -type f -name '*.html' | wc -l)" -gt 0 ]; then
            echo "[INFO] scan-build completed with warnings. Check the scan-build-reports artifact."
            exit 0
          else
            echo "[ERROR] No scan-build reports generated. Failing the workflow."
            exit 1
          fi
      - name: Check build success
        run: |
          if [ -f DemoIccMAX/Build/CMakeCache.txt ]; then
            echo "[✔] Build configuration exists."
          else
            echo "[✘] Build configuration failed."
            exit 1
          fi
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: master-build-linux
          path: DemoIccMAX/Build

      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: DemoIccMAX/Build/CMakeCache.txt

      - name: Exit Banner
        run: |
          echo "====================================="
          echo " Ubu Scan Build Workflow Completed "
          echo "====================================="
