# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/C++.gitlab-ci.yml

# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/

image: gcc

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
    - apt-get update -qq
    - apt-get install -y locales cmake pkg-config libxml2-dev

  script:
    - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
    - git clone https://github.com/nlohmann/json.git && (cd json && mkdir build && cd build && cmake -DBUILD_TESTING=OFF -DJSON_BuildTests=OFF .. && make install)
    - git checkout linux
    - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ../Build/Cmake
    - make

