###############################################################
#
## Copyright (©) 2024-2025 David H Hoyt. All rights reserved.
##                 https://srd.cx
##
## Last Updated: 10-MAY-2025 at 1030 EDT by David Hoyt (©)
#
## Intent: Issue113-SIPS
#
#
#
#
#
#
#
#
#
#
#
###############################################################


name: "Issue113-SIPS"

on:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build PoC Stub off xnu-research Branch for XNU-FUZZ
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Git Identity
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Install Dependencies
        run: |
          echo "=== Installing Build and Runtime Dependencies ==="
          brew install nlohmann-json libxml2 wxwidgets libtiff libpng jpeg
      - name: Get research for Stub Build for FUZZ
        run: |
          echo "=== Cloning off xnu-research Branch ==="
          git clone https://github.com/xsscx/PatchIccMAX.git
          cd PatchIccMAX
          git checkout research
          echo "=== DONE Cloning PatchIccMAX for research ==="
      - name: Configure with CMake (ASAN + Debug)
        run: |
          echo "=== Configuring from research ==="
          cd PatchIccMAX/Build
          export CC=clang
          export CXX=clang++
          export PATH="/usr/lib/llvm-17/bin:$PATH"
          echo "CC=gcc" >> $GITHUB_ENV
          echo "CXX=g++" >> $GITHUB_ENV
          clang++ --version
          clang --version
          sudo rm -rf /Library/Frameworks/Mono.framework/Headers/png.h
          cmake -DCMAKE_INSTALL_PREFIX="$HOME/.local" -DCMAKE_BUILD_TYPE=Debug Cmake/
      - name: Build research for FUZZ
        run: |
          echo "=== Starting Build ==="
          cd PatchIccMAX/Build
          make -j$(nproc)
      - name: Run Unit Tests (CI Harness)
        run: |
          echo "========= BEGIN OUTSIDE STUB ========="
          cd PatchIccMAX/Testing
          # Add Tools/* to PATH
          for d in ../Build/Tools/*; do
            [ -d "$d" ] && export PATH="$(realpath "$d"):$PATH"
          done
          echo "========= BEGIN INSIDE STUB ========="
          echo "=================== Running Checks off xnu-research Branch =========================================" 
          set +e
          echo "RUN file"
          echo -n "Found ICC files: "; find Issue113/ -type f -name "*.icc" -print0 | tee >(tr '\0' ' ') | while IFS= read -r -d '' f; do echo ">>> FILE: $f"; file "$f" || true; done
          echo "RUN sips"
          echo -n "Found ICC files: "; find Issue113/ -type f -name "*.icc" -print0 | tee >(tr '\0' ' ') | while IFS= read -r -d '' f; do echo ">>> SIPS: $f"; sips --verify "$f" || true; done
          echo "========= INSIDE STUB EXIT ========="
          EXIT_CODE=$?
          if [ "$EXIT_CODE" -ne 0 ]; then
          echo "PoC executed as expected with failure code $EXIT_CODE."
          else
          echo "Review Output."
          fi
          echo "========= OUTSIDE STUB EXIT ========="
      - name: Verify Build Output
        run: |
          echo "=== Verifying Build Result ==="
          if [ -f PatchIccMAX/Build/CMakeCache.txt ]; then
            echo "Build configuration exists."
          else
            echo "Build configuration failed."
            exit 1
          fi
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: patchiccmax-linux-binaries
          path: PatchIccMAX/Build

      - name: Upload CMake Logs
        uses: actions/upload-artifact@v4
        with:
          name: patchiccmax-cmake-log
          path: PatchIccMAX/Build/CMakeCache.txt
          
      - name: Summary Report
        if: always()
        run: |
          echo "### Ubuntu Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Build Directory: PatchIccMAX/Build/" >> $GITHUB_STEP_SUMMARY
          echo "- Artifacts Uploaded: iccmax-macos-clang" >> $GITHUB_STEP_SUMMARY
          echo "- Status: Success" >> $GITHUB_STEP_SUMMARY
