###############################################################
#
## Copyright (©) 2024-2025 David H Hoyt. All rights reserved.
##                 https://srd.cx
##
## Last Updated: 25-JULY-2025 1600Z by David Hoyt (©)
#
## Intent: 31Cmake
#
## TODO: Add Unit Test Suite
#
#
#
#
#
#
#
#
#
###############################################################

name: 31cmake

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    strategy:
      matrix:
        build_type: [Debug]

    steps:
      - uses: actions/checkout@v3

      - name: Cache build binaries
        uses: actions/cache@v3
        with:
          path: |
            PatchIccMAX\Build\Cmake\build
          key: cmake-build-${{ runner.os }}-${{ matrix.build_type }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            cmake-build-${{ runner.os }}-${{ matrix.build_type }}-
     
      - name: Prepend Debug Tools to PATH
        run: |
          dir
          pwd
          cd Testing
          pwd
          $tools = @(
            "IccApplyNamedCmm", "IccApplyProfiles", "IccApplyToLink", "IccDumpProfile",
            "IccFromCube", "IccFromXml", "IccJpegDump", "IccPngDump",
            "IccRoundTrip", "IccSpecSepToTiff", "IccTiffDump", "IccToXml",
            "IccV5DspObsToV4Dsp", "wxProfileDump"
          )
          foreach ($tool in $tools) {
            $env:PATH = "$env:GITHUB_WORKSPACE\PatchIccMAX\Tools\$tool\Debug;$env:PATH"
          }
      - name: Run Functional Test Suite
        run: |
          cd  Testing
          .\CreateAllProfiles.bat
          .\RunTests.bat
          cd CalcTest
          .\checkInvalidProfiles.bat
          .\runtests.bat
          cd ..
          cd Display
          .\RunProtoTests.bat
          cd ..
          cd HDR
          .\mkprofiles.bat
          cd ..
          cd mcs
          .\updateprev.bat
          .\updateprevWithBkgd.bat
          cd ..
          cd Overprint
          .\RunTests.bat
          cd ..
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iccmax-windows-msvc
          path: PatchIccMAX/build/**/*.@(exe|lib)

      - name: Summary Report
        if: always()
        run: |
          echo "### ICCMAX Windows Build" >> $env:GITHUB_STEP_SUMMARY
          echo "- Status: ${{ job.status }}" >> $env:GITHUB_STEP_SUMMARY
