###############################################################
#
## Copyright (©) 2024-2025 David H Hoyt. All rights reserved.
##                 https://srd.cx
##
## Last Updated: 25-JULY-2025 1600Z by David Hoyt (©)
#
## Intent: 4Cmake
#
## TODO: Add Unit Test Suite
#
#
#
#
#
#
#
#
#
###############################################################

name: 4Cmake

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    strategy:
      matrix:
        build_type: [Release]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache vcpkg packages
        uses: actions/cache@v3
        with:
          path: |
            C:\vcpkg\installed
            C:\vcpkg\buildtrees
            C:\vcpkg\downloads
          key: vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-

      - name: Cache build binaries
        uses: actions/cache@v3
        with:
          path: |
            DemoIccMAX\Build\Cmake\build
          key: cmake-build-${{ runner.os }}-${{ matrix.build_type }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            cmake-build-${{ runner.os }}-${{ matrix.build_type }}-

      - name: Clone Official DemoIccMAX
        run: |
          git clone https://github.com/InternationalColorConsortium/DemoIccMAX.git
          cd DemoIccMAX
          vcpkg integrate install
          vcpkg install

      - name: Configure
        run: |
          cd DemoIccMAX
          cd Build\Cmake
          cmake -B build -S . -G "Visual Studio 17 2022" -A x64 ^
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ^
          -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: |
          cd DemoIccMAX\Build\Cmake
          cmake --build build --config ${{ matrix.build_type }}
          dir /s /b *.exe *.lib

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iccmax-windows-msvc
          path: DemoIccMAX\Build\Cmake\build\**\*.{exe,lib}

      - name: Summary Report
        if: always()
        run: |
          echo "### Windows Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Build Directory: DemoIccMAX\\Build\\Cmake\\build\\" >> $GITHUB_STEP_SUMMARY
          echo "- Artifacts Uploaded: iccmax-windows-msvc" >> $GITHUB_STEP_SUMMARY
          echo "- Status: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
