###############################################################
#
## Copyright (©) 2024-2025 David H Hoyt. All rights reserved.
##                 https://srd.cx
##
## Last Updated: 25-JULY-2025 1600Z by David Hoyt (©)
#
## Intent: 5Cmake
#
## TODO: Add Unit Test Suite
#
#
#
#
#
#
#
#
#
###############################################################

name: 5Cmake

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    strategy:
      matrix:
        build_type: [Release]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache vcpkg packages
        uses: actions/cache@v3
        with:
          path: |
            C:\vcpkg\installed
            C:\vcpkg\buildtrees
            C:\vcpkg\downloads
          key: vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-

      - name: Cache build binaries
        uses: actions/cache@v3
        with:
          path: |
            DemoIccMAX\Build\Cmake\build
          key: cmake-build-${{ runner.os }}-${{ matrix.build_type }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            cmake-build-${{ runner.os }}-${{ matrix.build_type }}-

      # Clone DemoIccMAX and setup vcpkg
      - name: Clone and setup repositories (Windows)
        shell: pwsh
        run: |
          git clone https://github.com/InternationalColorConsortium/DemoIccMAX.git
          cd DemoIccMAX
          git checkout vcpkg
          Remove-Item -Force vcpkg.json -ErrorAction SilentlyContinue
          cd ..
      
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg integrate install
          cd ..
      
      # Install iccdev from overlay port
      - name: Install iccdev (Windows)
        shell: pwsh
        run: |
          .\vcpkg\vcpkg.exe install  --overlay-ports=DemoIccMAX\ports
          .\vcpkg\vcpkg.exe list
          Write-Host "iccdev install completed"


      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iccmax-windows-msvc
          path: DemoIccMAX\Build\Cmake\build\**\*.{exe,lib}

      - name: Summary Report
        if: always()
        run: |
          echo "### Windows Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Build Directory: DemoIccMAX\\Build\\Cmake\\build\\" >> $GITHUB_STEP_SUMMARY
          echo "- Artifacts Uploaded: iccmax-windows-msvc" >> $GITHUB_STEP_SUMMARY
          echo "- Status: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
