###############################################################
#
## Copyright (©) 2024 David H Hoyt. All rights reserved.
##                 https://srd.cx
##
## Last Updated: 04-AUGUST-2025 at 0700 EDT by David Hoyt (©)
#
#
#
## Intent: brew install check
#
## 
#
#
###############################################################

name: "BREW Install iccdev"

on:
  workflow_dispatch:

jobs:
  brew-check:
    name: "Verify Homebrew and Install iccdev"
    runs-on: macos-14

    steps:
      - name: Log Basic System Info
        run: |
          echo "User: $(whoami)"
          echo "Platform: $(uname -a)"
          echo "Date: $(date)"
          echo "Shell: $SHELL"
          echo "Path: $PATH"

      - name: Check for Homebrew
        run: |
          if ! command -v brew &> /dev/null; then
            echo "Homebrew not found!"
            exit 1
          fi
          echo "Homebrew is installed."

      - name: Show Homebrew Info
        run: |
          brew --version
          brew config
          brew doctor || echo "brew doctor exited with non-zero"

      - name: Install iccdev
        run: |
          brew update
          brew install iccdev

      - name: Validate iccdev Installation
        run: |
          brew list --versions iccdev || echo "iccdev not listed"
          which iccdev || echo "iccdev binary not found in PATH"
          iccdev --version || echo "iccdev command failed"
