###############################################################
#
## Copyright (©) 2024-2025 David H Hoyt. All rights reserved.
##                 https://srd.cx
##
## Last Updated: 02-MAY-2025 1800 EDT by David Hoyt (©)
#
## Intent: Dev-Dumper
#
## TODO: Refactor for all Windows & UNIX Device Reporting
#
#
#
#
#
#
#
#
#
###############################################################

name: "Dev-Dumper"

on:
  workflow_dispatch:

jobs:
  build-macos:
    name: Build research
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git anonymous identity
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
    - name: Clone the PatchIccMAX repository
      run: |
          git clone https://github.com/xsscx/PatchIccMAX.git
          cd PatchIccMAX
          git checkout research
          brew install nlohmann-json libxml2 wxwidgets libtiff libpng jpeg
    - name: Configure research
      run: |
        mkdir -p PatchIccMAX/Build
        cd PatchIccMAX/Build
        sudo rm -rf /Library/Frameworks/Mono.framework/Headers/png.h
        export CXX=clang++
        cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_FLAGS="-g -fsanitize=address,undefined -fno-omit-frame-pointer -Wextra -Wno-unused-parameter -Wno-unused-variable"  -Wno-dev -DENABLE_TOOLS=ON -DENABLE_SHARED_LIBS=ON -DENABLE_STATIC_LIBS=ON -DENABLE_TESTS=ON  -DENABLE_INSTALL_RIM=ON -DENABLE_ICCXML=ON Cmake/
    - name: Build research
      run: |
        cd PatchIccMAX/Build
        make -j$(sysctl -n hw.ncpu)
        pwd
        ls
        cd ../Testing
        pwd
        ls
        echo "=== Running CI Stub Test Harness ==="
         for d in ../Build/Tools/*; do
          [ -d "$d" ] && export PATH="$(realpath "$d"):$PATH"
         done
        sh CreateAllProfiles.sh
        # /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/xsscx/PatchIccMAX/refs/heads/pr129/contrib/UnitTest/iccMAX-cicd-build-checks.sh)"
        # /bin/zsh -c "$(curl -fsSL https://raw.githubusercontent.com/xsscx/PatchIccMAX/refs/heads/pr129/contrib/UnitTest/iccDumpProfile_checks.zsh)"
        # wget https://raw.githubusercontent.com/xsscx/PatchIccMAX/refs/heads/pr120/contrib/UnitTest/iccMAX-cicd-build-checks.sh
        # bash iccMAX-cicd-build-checks.sh > ../test-suite.log 2>&1 || echo "Tests failed, continuing to upload logs."
        echo "========= CI STUB TESTS COMPLETE ========="
    - name: Upload Testing Directory
      uses: actions/upload-artifact@v4
      with:
        name: PatchIccMAX-Testing
        path: PatchIccMAX/Testing/
    - name: Summary Report
      if: always()
      run: |
          echo "### macOS Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Build Directory: PatchIccMAX/Build/" >> $GITHUB_STEP_SUMMARY
          echo "- Artifacts Uploaded: iccmax-macos-clang" >> $GITHUB_STEP_SUMMARY
          echo "- Status: Success" >> $GITHUB_STEP_SUMMARY
