###############################################################
#
## Copyright (©) 2024-2025 David H Hoyt. All rights reserved.
##                 https://srd.cx
##
## Last Updated: 02-MAY-2025 1800 EDT by David Hoyt (©)
#
## Intent: iccDumpProfile
#
## TODO: Refactor for all Windows & UNIX Device Reporting
#
#
#
#
#
#
#
#
#
###############################################################

name: "iccDumpProfile"

on:
  workflow_dispatch:

jobs:
  build-macos:
    name: Build XNU-Unit-Test
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git anonymous identity
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Clone the PatchIccMAX repository
      run: |
        git clone https://github.com/xsscx/PatchIccMAX.git
        cd PatchIccMAX

    - name: Install dependencies
      run: brew install nlohmann-json libxml2 wxwidgets libtiff libpng jpeg

    - name: Restore cached build
      uses: actions/cache@v4
      id: cache-build
      with:
        path: PatchIccMAX/Build
        key: build-macos-iccmax-${{ hashFiles('**/Cmake/**', '**/CMakeLists.txt') }}

    - name: Configure the build (only if cache miss)
      if: steps.cache-build.outputs.cache-hit != 'true'
      run: |
        mkdir -p PatchIccMAX/Build
        cd PatchIccMAX/Build
        sudo rm -rf /Library/Frameworks/Mono.framework/Headers/png.h || true
        export CXX=clang++
        cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local \
              -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
              -DCMAKE_CXX_FLAGS="-g -fsanitize=address,undefined -fno-omit-frame-pointer -Wextra -Wno-unused-parameter -Wno-unused-variable" \
              -Wno-dev \
              -DENABLE_TOOLS=ON \
              -DENABLE_SHARED_LIBS=ON \
              -DENABLE_STATIC_LIBS=ON \
              -DENABLE_TESTS=ON \
              -DENABLE_INSTALL_RIM=ON \
              -DENABLE_ICCXML=ON \
              Cmake/

    - name: Build the project
      if: steps.cache-build.outputs.cache-hit != 'true'
      run: |
        cd PatchIccMAX/Build
        make -j$(sysctl -n hw.ncpu)

    - name: Run Test Suite
      run: |
        cd PatchIccMAX/Testing
        for d in ../Build/Tools/*; do
          [ -d "$d" ] && export PATH="$(realpath "$d"):$PATH"
        done
        chmod +x CreateAllProfiles.sh
        ./CreateAllProfiles.sh
        chmod +x RunTests.sh
        ./RunTests.sh
        # /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/xsscx/PatchIccMAX/refs/heads/research/contrib/UnitTest/iccMAX-cicd-build-checks.sh)"
        # /bin/zsh -c "$(curl -fsSL https://raw.githubusercontent.com/InternationalColorConsortium/DemoIccMAX/refs/heads/master/contrib/UnitTest/iccDumpProfile_checks.zsh)"
        echo "========= CI STUB TESTS COMPLETE ========="

    - name: Upload Testing Directory
      uses: actions/upload-artifact@v4
      with:
        name: PatchIccMAX-Testing
        path: PatchIccMAX/Testing/

    - name: Summary Report
      if: always()
      run: |
        echo "### macOS Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "- Build Directory: PatchIccMAX/Build/" >> $GITHUB_STEP_SUMMARY
        echo "- Artifacts Uploaded: iccmax-macos-clang" >> $GITHUB_STEP_SUMMARY
        echo "- Status: Success" >> $GITHUB_STEP_SUMMARY
