###############################################################
#
## Copyright (©) 2024-2025 David H Hoyt. All rights reserved.
##                 https://srd.cx
##
## Last Updated: 05-MAY-2025 at 1030 EDT by David Hoyt (©)
#
## Intent: mtx-research-stub
#
#
#
#
#
#
#
#
#
#
#
###############################################################

name: "mtx-research-stub"

on:
  workflow_dispatch:

jobs:
  build-test-matrix:
    name: mtx-research-stub ${{ matrix.macos }} ${{ matrix.arch }}
    runs-on: macos-${{ matrix.macos }}
    strategy:
      fail-fast: false
      matrix:
        macos: [13, 14]
        arch: [x86_64, arm64]

    steps:
      - name: Checkout Repository for cmake branch matrix tests
        uses: actions/checkout@v4

      - name: Set Up Git Identity for mtx-research-stub
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Install Dependencies
        run: |
          echo "=== Installing Build and Runtime Dependencies ==="
          brew install nlohmann-json libxml2 wxwidgets libtiff libpng jpeg
      - name: Get cmake branch
        run: |
          echo "=== Cloning off research Branch for mtx-research-stub ==="
          git clone https://github.com/xsscx/PatchIccMAX.git
          cd PatchIccMAX
          git checkout cmake
          echo "=== DONE Cloning PatchIccMAX for mtx-research-stub ==="
      - name: Configure with CMake (ASAN + Debug)
        run: |
          echo "=== Configuring mtx-research-stub ==="
          cd PatchIccMAX/Build
          export CC=clang
          export CXX=clang++
          export PATH="/usr/lib/llvm-17/bin:$PATH"
          echo "CC=gcc" >> $GITHUB_ENV
          echo "CXX=g++" >> $GITHUB_ENV
          clang++ --version
          clang --version
          sudo rm -rf /Library/Frameworks/Mono.framework/Headers/png.h
          cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_FLAGS="-g -fsanitize=address,undefined -fno-omit-frame-pointer -Wextra -Wno-unused-parameter -Wno-unused-variable"  -Wno-dev -DENABLE_TOOLS=ON -DENABLE_SHARED_LIBS=ON -DENABLE_STATIC_LIBS=ON -DENABLE_TESTS=ON  -DENABLE_INSTALL_RIM=ON -DENABLE_ICCXML=ON Cmake/
      - name: Build research for mtx-research-stub
        run: |
          echo "=== Starting Build ==="
          cd PatchIccMAX/Build
          make -j$(nproc)
      - name: Run Unit Tests (CI Harness)
        run: |
          echo "========= BEGIN OUTSIDE COV STUB for mtx-research-stub ========="
          echo "========= BEGIN INSIDE STUB for mtx-research-stub =============="
          cd PatchIccMAX/Testing
          # Add Tools/* to PATH
          for d in ../Build/Tools/*; do
            [ -d "$d" ] && export PATH="$(realpath "$d"):$PATH"
          done
          echo "=================== Running Checks off xnu-research Branch for mtx-research-stub =========================================" 
          set +e
          echo "========= BEGIN mtx-research-stub ========"
          pwd
          echo "Creating Display/Rec2100HlgNarrow.icc"
          cd Display
          iccFromXml Rec2100HlgNarrow.xml Rec2100HlgNarrow.icc
          cd ..
          echo "Measurement: sips --verify Display/Rec2100HlgNarrow.icc"
          sips --verify Display/Rec2100HlgNarrow.icc
          
          echo "Measurement: iccDumpProfile -v Display/Rec2100HlgNarrow.icc"
          iccDumpProfile -v Display/Rec2100HlgNarrow.icc
          
          echo "Measurement: iccRoundTrip Display/Rec2100HlgNarrow.icc"
          iccDumpProfile Display/Rec2100HlgNarrow.icc
          echo "========= EXIT  mtx-research-stub ========"
          echo "========= BEGIN INNER Issue 113 STUB ========"
          set +e
          echo "RUN file"
          echo -n "Found ICC files: "; find Issue113/ -type f -name "*.icc" -print0 | tee >(tr '\0' ' ') | while IFS= read -r -d '' f; do echo ">>> FILE: $f"; file "$f" || true; done
          echo "RUN sips"
          echo -n "Found ICC files: "; find Issue113/ -type f -name "*.icc" -print0 | tee >(tr '\0' ' ') | while IFS= read -r -d '' f; do echo ">>> SIPS: $f"; sips --verify "$f" || true; done
          echo "========= INNER STUB Issue 113 EXIT ========="
          echo "========= INSIDE STUB mtx-research-stub EXIT =================="
 
          EXIT_CODE=$?
          if [ "$EXIT_CODE" -ne 0 ]; then
          echo "mtx-research-stub executed as expected with failure code $EXIT_CODE."
          else
          echo "mtx-research-stub unexpectedly succeeded. Please verify runtime behavior."
          fi
          echo "========= OUTSIDE STUB mtx-research-stub EXIT ========="
      - name: Verify Build Output
        run: |
          test -f PatchIccMAX/Build/CMakeCache.txt && echo "Build OK" || (echo "Missing build cache" && exit 1)

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mtx-research-stub-${{ matrix.macos }}-${{ matrix.arch }}
          path: PatchIccMAX/Build

      - name: Upload CMake Logs for mtx-research-stub
        uses: actions/upload-artifact@v4
        with:
          name: cmake-log-${{ matrix.macos }}-${{ matrix.arch }}
          path: PatchIccMAX/Build/CMakeCache.txt

      - name: Matrix Summary
        if: always()
        run: |
          echo "## for mtx-research-stub ${{ matrix.macos }} ${{ matrix.arch }} Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Directory: PatchIccMAX/Build/" >> $GITHUB_STEP_SUMMARY
          echo "- RAN: mtx-research-stub: Yes" >> $GITHUB_STEP_SUMMARY          
