###############################################################
#
## Copyright (©) 2024-2025 David H Hoyt. All rights reserved.
##                 https://srd.cx
##
## Last Updated: 03-MAY-2025 at 0700 EDT by David Hoyt (©)
#
## Intent: npm smoke test
#
##

#
#
###############################################################

name: "NPMTest3"
on:
  workflow_dispatch:

jobs:
  iccwasm-test:
    name: "Install & Verify iccwasm"
    runs-on: macos-14

    steps:
      - name: Log Node & System Info
        run: |
          echo "Node: $(node -v)"
          echo "NPM: $(npm -v)"
          echo "User: $(whoami)"
          echo "Platform: $(uname -a)"
          echo "Working Dir: $(pwd)"

      - name: Init test directory
        run: |
          mkdir iccwasm-test && cd iccwasm-test
          npm init -y

      - name: Install iccwasm
        working-directory: ./iccwasm-test
        run: npm install iccwasm

      - name: List installed files
        working-directory: ./iccwasm-test
        run: ls -R node_modules/iccwasm || echo "Install missing or failed"

      - name: Show installed scripts or JS
        working-directory: ./iccwasm-test/node_modules/iccwasm
        run: |
          echo "Top-level files:"
          ls -lh
          echo "All WASM & JS:"
          find . -type f \( -name "*.js" -o -name "*.wasm" \)

      - name: Dump package metadata
        working-directory: ./iccwasm-test
        run: cat package.json
