###############################################################
#
## Copyright (©) 2024 David H Hoyt. All rights reserved.
##                 https://srd.cx
##
## Last Updated: 22-APRIL-2025 1422 EDT by David Hoyt (©)
#
## Intent: PR129-xnu-debug-scan
#
## TODO: Refactor for XNU Universal Build
#
#
###############################################################

name: "PR129-SB"

on:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build and Test Linux PR129 with scan-build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: 📥 Checkout PR129
        uses: actions/checkout@v4
        with:
          ref: pr129
      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake gcc g++ clang clang-tools libpng-dev libxml2 libxml2-dev libtiff-dev nlohmann-json3-dev libwxgtk3.2-dev wx-common python3 python3-pip curl git llvm
      # Ensure scan-build is in PATH
      - name: Ensure scan-build is installed and accessible
        run: |
          export PATH="/usr/lib/llvm-17/bin:$PATH"
          which scan-build || echo "? scan-build not found"
          scan-build --version || echo "? scan-build version check failed"
      # Configure the build with scan-build
      - name: Configure the build with scan-build
        run: |
          ls
          cd Build
          pwd
          ls
          export CC=clang
          export CXX=clang++
          export PATH="/usr/lib/llvm-17/bin:$PATH"
          scan-build cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_BUILD_TYPE=Release -DENABLE_TOOLS=ON -Wno-dev Cmake/
      # Run scan-build for static analysis
      - name: Run scan-build for static analysis
        run: |
          pwd
          ls
          cd Build
          pwd
          ls
          export PATH="/usr/lib/llvm-17/bin:$PATH"
          scan-build --status-bugs --keep-going -o scan-build-reports make -j$(nproc) || true
        continue-on-error: true  # Allow the step to complete even if issues are found

      # Upload scan-build reports
      - name: Upload scan-build reports
        uses: actions/upload-artifact@v4
        with:
          name: scan-build-reports
          path: Build/scan-build-reports

      # Upload built binaries as artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: master-build-linux
          path: Build

      # Upload build logs
      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: PatchIccMAX/Build/CMakeCache.txt
