###############################################################
#
## Copyright (©) 2024-2025 David H Hoyt. All rights reserved.
##                 https://srd.cx
##
## Last Updated:05-AUGUST-2025 at 1100Z by David Hoyt (©)
#
## Intent: VCPKG Ubuntu MTX Test
#
## TODO: 
#
#
###############################################################

name: "VCPKG Ubu MTX Smoke Test"

on:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build and Test Linux on Ubuntu ${{ matrix.ubuntu }}
    runs-on: ${{ matrix.ubuntu }}
    strategy:
      fail-fast: false
      matrix:
        ubuntu: [ubuntu-22.04, ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git anonymous identity
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential cmake clang git python3 curl unzip tar \
          libxml2-dev libtiff-dev nlohmann-json3-dev libjpeg-dev libpng-dev \
          libtool m4 autoconf automake libltdl-dev libx11-dev libxft-dev \
          libxext-dev libxi-dev libxtst-dev libxrandr-dev

    - name: Clone and prepare DemoIccMAX with vcpkg
      run: |
        git clone https://github.com/xsscx/PatchIccMAX.git
        cd PatchIccMAX
        git checkout vcpkg
        rm -f vcpkg.json
        cd ..
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
        ./vcpkg integrate install
        cd ../PatchIccMAX
        ../vcpkg/vcpkg install --overlay-ports=ports
