###############################################################
#
## Copyright (©) 2024-2025 David H Hoyt. All rights reserved.
##                 https://srd.cx
##
## Last Updated: 02-AUGUST-2025 at 1400Z by David Hoyt (©)
#
## Intent: WASM-Release
#
## 
#
#
###############################################################

name: "WASM-Release"

on:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build and Test Linux Master Branch
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up Git anonymous identity
    - name: Set up Git anonymous identity
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
    # Clone the DemoIccMAX repository
    - name: Run WASM Build Script
      run: |
       git clone https://github.com/emscripten-core/emsdk.git
       cd emsdk
       git pull
       ./emsdk install latest
       ./emsdk activate latest
       source ./emsdk_env.sh
       /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/InternationalColorConsortium/DemoIccMAX/refs/heads/wasm/wasm_remote_build.sh)"
    # Run additional system info and validation commands
    - name: Gather system information
      run: |
        uname -a
        cat /etc/os-release
        gcc -v
        lscpu
        free -m
        df -h
    # Upload built binaries as artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: master-build-linux
        path: DemoIccMAX/Build

    # Upload build logs
    - name: Upload build logs
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: DemoIccMAX/Build/CMakeCache.txt
