###############################################################
#
## Copyright (©) 2024-2025 David H Hoyt. All rights reserved.
##                 https://srd.cx
##
## Last Updated: 08-AUGUST-2025 at 2300Z by David Hoyt (©)
#
## Intent: vcpkg ports file windows smoke test 5
#
## TODO: 
#
#
###############################################################

name: "VCPKG Windows Test"

on:
  workflow_dispatch:

jobs:
  build-windows:
    name: PoC on Windows
    runs-on: windows-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Git anonymous identity
      - name: Set up Git anonymous identity
        shell: pwsh
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      # Clone PatchIccMAX repository and checkout vcpkg branch
      - name: Clone PatchIccMAX repository
        shell: pwsh
        run: |
          git clone https://github.com/xsscx/PatchIccMAX.git
          cd PatchIccMAX
          git checkout vcpkg
          Remove-Item -Force -ErrorAction SilentlyContinue vcpkg.json
          pwd
          cd ..

          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg.exe integrate install
          pwd
          Get-ChildItem ..\

          cd ..\PatchIccMAX
          pwd
          Get-ChildItem

          # Install overlay port using the SAME vcpkg instance and explicit triplet
          ..\vcpkg\vcpkg.exe --classic --overlay-ports=ports  install iccdev --debug
          ..\vcpkg\vcpkg.exe --classic --overlay-ports=ports  install iccdev --debug
          
          # Verify using the SAME instance/root + triplet for consistency
          ..\vcpkg\vcpkg.exe list --triplet x64-windows || exit 0
