###############################################################
#
## Copyright (©) 2024-2025 David H Hoyt. All rights reserved.
##                 https://srd.cx
##
## Last Updated: 28-MAR-2025 1800 EDT by David Hoyt (©)
#
## Intent: XNU-issue113
#
## TODO: Refactor for all Windows & UNIX Device Reporting
#
#
#
#
#
#
#
#
#
###############################################################

name: "XNU-issue113"

on:
  workflow_dispatch:

jobs:
  build-macos:
    name: Build PR130
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git anonymous identity
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
    - name: Clone the PatchIccMAX repository
      run: |
          git clone https://github.com/xsscx/PatchIccMAX.git
          cd PatchIccMAX
          git checkout issue113
          brew install nlohmann-json libxml2 wxwidgets libtiff libpng jpeg
    - name: Configure the build with CMake (strict + logged) PR130
      run: |
        mkdir -p PatchIccMAX/Build
        cd PatchIccMAX/Build
        sudo rm -rf /Library/Frameworks/Mono.framework/Headers/png.h
        export CXX=clang++
        cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_FLAGS="-g -fsanitize=address,undefined -fno-omit-frame-pointer -Wextra -Wno-unused-parameter -Wno-unused-variable"  -Wno-dev -DENABLE_TOOLS=ON -DENABLE_SHARED_LIBS=ON -DENABLE_STATIC_LIBS=ON -DENABLE_TESTS=ON  -DENABLE_INSTALL_RIM=ON -DENABLE_ICCXML=ON Cmake/
    - name: Build and Run Test Suite
      run: |
        cd PatchIccMAX/Build
        make -j$(sysctl -n hw.ncpu)
        pwd
        ls
        cd ../Testing
        pwd
        ls
        echo "=== Running CI Stub Test Harness ==="
         for d in ../Build/Tools/*; do
          [ -d "$d" ] && export PATH="$(realpath "$d"):$PATH"
         done
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/xsscx/PatchIccMAX/refs/heads/pr128/contrib/UnitTest/iccMAX-cicd-build-checks.sh)"
        # wget https://raw.githubusercontent.com/xsscx/PatchIccMAX/refs/heads/pr120/contrib/UnitTest/iccMAX-cicd-build-checks.sh
        # bash iccMAX-cicd-build-checks.sh > ../test-suite.log 2>&1 || echo "Tests failed, continuing to upload logs."
        echo "========= CI STUB TESTS COMPLETE ========="
